project_id = "svozqrjhwaohfmbkhpig"

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.send-daily-summary]
verify_jwt = false

[functions.send-report-email]
verify_jwt = false

[functions.send-task-notifications]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.send-user-invitation]
verify_jwt = false
